# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99420499166e7e835714ddb3badea2cab85fb33079964fe05b83aedaacf7daaeb141e5fe7ec6ea9c385c23a5ab2d9d1d2b1c52a929ee0c23f15476a6302e5410

test:
  secret_key_base: ba9469d6227ee4e6f9bc0fbcccd934e700b6ac37312c3da5f3f9ce540ce7851741d4171f9d3232019d91e9d57756844253327781679c227b626c87c9df0e2827

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
